# -*- coding: utf-8 -*-
"""Week1-Py-Intro-C1-Colabs-Demo-004.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1woOClzpEyusCgBimFptiYIwnHMN6KyCS

Intro to python 3.0

Markdown text intro
"""

print("Intro to python 3.0")

#https://www.w3schools.com/python/python_variables.asp

x = 5
y = "John"

print(x)
print(y)