# -*- coding: utf-8 -*-
"""Week1-Py-Intro-C1-Colabs-Demo-003.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVR4RTDqVC5kUm4_UvwTe-_K0jz55gfT

Intro to Python 3.0

Markdown Text Intro

# Text Title 1
## Text Title 1
### Text Title 1

**Text bold**

Items
- item 1
- item 2

<p>
Html code
"""

print("python intro 3.0")

# single line comment

"""

multi line

comment

"""