# -*- coding: utf-8 -*-
"""Week1-Py-Intro-C1-Colabs-vsCode-002.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8jHYg4D3TMmDH7ZwX6VRcYnuQyrpYAQ

#Python Course I - Weekly class demos and Exercises summary  
- (Mon, Wed) - (8am-10:30am) - (2.5h class/demos/labs) / 30 min practice
- Course I - 7 weeks
- Course II - 10 weeks

#Github Course Notebook Refence

https://github.com/deanliit/10-24-Python-Intro-to-Advanced

#Weekly Topics
 - intro to google colabsl, vs.code

#Weekly Homework , Class Assignment, Class Project
- Reading/review
  - w3schools reference
  - https://www.w3schools.com/python/
  - pdf ebook ref

- practice labs
 - create intro python code using google colabs
   - ie: print, markdown text
   
- exercises , course book pages
- pages:
   -

## Python references
https://www.w3schools.com/python/python_intro.asp
- Course book

### Class Quiz - Email link to google forms

<pre>
- 3 quizzes - similar to python entry level quiz
- multiple choice
- 5 multiple choice quesitons = 70%
- 1 code fill-in question
-- write code is vs.code - copy code in quiz
-- small example program -- %30
example: write a progarm to compute 2 values
optional/extra: create a startup program
input: prompt for each input
output: display items and total
hint:

name = input("name")
email = input("email")
print(f"{name} {email}")
#print(name, email)

- take home
- approx. 1 week to complete
- submit answers with quiz
- quiz is similar question to python Entry Level Exam and some question from Associate Exam
- no questions on Data Science, SQL, HTML, ETL
- review quiz in class

</pre>

Introduction to Python Topic Summary
- -------------------------------------------------------------

Introduction to Python
- https://www.w3schools.com/python/python_intro.asp

# download python 3.x or latest
- https://www.python.org/downloads/

google colabs notebook introduction
- similar to jypyter notebook
- https://colab.research.google.com/

vs.code - extension
- code editor
- https://code.visualstudio.com/download

Pycharm
- https://www.jetbrains.com/pycharm/download/?section=windows
- code editor

pyscripter
- https://sourceforge.net/projects/pyscripter/
- pre-install python with editor
- run python 3+ in editor
- install l=python libraries in the editor environment instead of local computer

<pre>
---------------------------------------------
#Course I Module Summary
-----------------------------------------------

https://www.w3schools.com/python/python_intro.asp

# Module 1
---------------------------
Python fundamentals
Data type
Variables
Input
for, while loop
Other

# Module 2
----------------------------
Array index
Slicers, list comprehension  
Functions
File input
Other

# Module 3
--------------------------------
Data structures
Array, set, list, tuple, map
Classes
Lamda
Other

#optional - Module 4
---------------------------------
Intro to data analyst using python
Pandas, numpy
SQL
Other

</pre>

Q/A
- ---------------

Questions
- eamil questions
- firday - q/a via google meeting

### Intro to google colabs notebook
- uses markdown text
  - markdown - simplified version of html
  - h1, title, bold, lists
- google virtual computer: linux os
- write python code
- schedule notebooks ie: batch programs
- can write notebook code in other languages
  - javascript, R, SQL
  - javs, other languages
- each colab notbook is similar to 1 python fil1
  - codes from previous cell above can be access be the current cell
  - example: varible created in a previous cell can be access by a cell below.
"""

#introduction to google colabs

# introduction to vs.code